gui:
  language: 'en'
gui:
  showIcons: true
customCommands:
  - key: 'C'
    command: "aicommits --type conventional"
    context: 'files'
    subprocess: true
    description: 'commit changes using git editor(Custom Command)'
