snippets:
  # snippet and keyword abbrev
  - name: docker up
    keyword: dud
    snippet: docker-compose up -d
  - name: docker up
    keyword: dur
    snippet: RAILS_ENV=test docker-compose up -d app
  - name: git status
    keyword: gs
    snippet: git status --short --branch
  - name: git pull
    keyword: gp
    snippet: git pull
  - name: push
    keyword: gps
    snippet: git push --force-with-lease --force-if-includes 
  - name: push origin
    keyword: gpo
    snippet: git push --force-with-lease --force-if-includes origin 
  - name: git switch
    keyword: gc
    snippet: git switch {{branch}}
  - name: git switch previous branch 
    keyword: gb
    snippet: git switch -
  - name: git checkout -f
    keyword: gcf
    snippet: git checkout -f
  - name: git pull develop
    keyword: gpd
    snippet: git pull origin develop-valuation-of-assets
  - name: git make branch
    keyword: gcb
    snippet: git checkout -b 
  # snippet with placeholder
  - name: git commit message
    keyword: gcim
    snippet: git commit -m '{{commit_message}}'
  - name: git add . && git commit
    keyword: gac
    snippet: git add . && git commit
  - name: git add . && aicommits
    keyword: gaa
    snippet: git add . && aicommits --type conventional
  - name: create PR
    keyword: gpr
    snippet: gh pr create
  - name: create PR with base 
    keyword: gprb
    snippet: gh pr create --base 
  - name: "null"
    keyword: "null"
    snippet: ">/dev/null 2>&1"

    # auto expand condition
    # If not defined, it is only valid at the beginning of a line.
    context:
      lbuffer: '.+\s'
      # rbuffer: ''
  - name: branch
    keyword: B
    snippet: git symbolic-ref --short HEAD
    context:
      lbuffer: '^git\s+checkout\s+'
    evaluate: true
  - name: push master
    keyword: gpuom
    snippet: git push origin master
  - name: pull master
    keyword: gpupm
    snippet: git pull origin master
  - name: push origin branch
    keyword: gpso
    snippet: git push origin {{branch}}
  - name: pull origin branch
    keyword: gpuo
    snippet: git pull origin {{branch}}
  - name: pull origin develop
    keyword: gpd
    snippet: git pull origin develop
  - name: qmk compile
    keyword: qc
    snippet: qmk compile -kb jisplit89 -km chimera
  - name: lazygit
    keyword: lg
    snippet: lazygit
  - name: aider
    keyword: ad
    snippet: aider --no-auto-commits --4turbo
  - name: commit.sh
    keyword: cmt
    snippet: ~/repos/private_dotfiles/mac/scripts/commit_dotfiles.sh
  - name: deploy.sh
    keyword: dpl
    snippet: ~/repos/private_dotfiles/mac/scripts/deploy_dotfiles.sh
  - name: php artisan migration
    keyword: pam
    snippet: php artisan migrate
  - name: migration
    keyword: mam
    snippet: ./mac artisan migrate
  - name: migration rollback
    keyword: mamr
    snippet: ./mac artisan migrate:rollback
  - name: make migration
    keyword: mamm
    snippet: ./mac artisan make:migration 

completions:
  - name: kill
    patterns: 
      - "^kill( -9)? $"
    sourceCommand: "ps -ef | sed 1d"
    options:
      --multi: true
      --prompt: "'Kill Process> '"
    callback: "awk '{print $2}'"
